version: "3"

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: pagoda_web
    ports:
      - "8000:8000"
    depends_on:
      - cache
      - db
    volumes:
      - ./:/app
  cache:
    image: "redis:alpine"
    container_name: pagoda_cache
    ports:
      - "6379:6379"
  db:
    # PG 16 is currenly not supported https://github.com/ent/ent/issues/3750
    image: postgres:15-alpine
    container_name: pagoda_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=app
